server:
  port: 8081

spring:
  application:
    name: Campus Price - Spring Boot
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/campusprice_sql?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: xjying11

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
